name: Get Public PR Comments

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  get-pr-comments:
    runs-on: ubuntu-latest

    steps:
    - name: Get PR comments
      id: get_pr_comments
      run: |
        # Define variables
        PR_NUMBER=${{ github.event.pull_request.number }}
        REPO=${{ github.repository }}
        GITHUB_API_URL="https://api.github.com/repos/${REPO}/issues/${PR_NUMBER}/comments"

        # Fetch PR comments using GitHub API without authentication for public repos
        response=$(curl -s -H "Accept: application/vnd.github.v3+json" "$GITHUB_API_URL")
       
        # Extract comment bodies and concatenate them
        COMMENTS=$(echo "$response" | jq -r '.[].body' | tr '\n' ' ')
       
        # Output comments
        echo "PR_COMMENTS=${COMMENTS}" >> $GITHUB_ENV

    - name: Display PR comments
      run: |
        echo "The PR comments are: ${{ env.PR_COMMENTS }}"
