name: Get Public PR Comments

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  get-pr-comments:
    runs-on: ubuntu-latest

    steps:
    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install gh

    - name: Get Public PR comments
      id: get_pr_comments
      run: |
        # Define PR number
        PR_NUMBER=${{ github.event.pull_request.number }}
        
        # Fetch PR comments using GitHub CLI
        COMMENTS=$(gh pr view $PR_NUMBER --comments --json body --jq '.[] | .body' | tr '\n' ' ')
        
        # Output comments
        echo "PR_COMMENTS=${COMMENTS}" >> $GITHUB_ENV

    - name: Display PR comments
      run: |
        echo "The PR comments are: ${{ env.PR_COMMENTS }}"
