name: List PR Commits

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  list-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List PR commits
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          COMMITS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/commits")

          echo "Commits in PR #$PR_NUMBER:"
          echo "$COMMITS" | jq '.[] | "- \(.commit.message)"'

      - name: Save commits to output
        id: save-commits
        run: |
          echo "::set-output name=commits::$(echo "$COMMITS" | jq -r 'map(.commit.message) | join(", ")')"
