name: My First Example

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Welcome Message
              run: |
                echo "Welcome first Workflow job"
                ls -lrth
                cat README.md
                shell: bash
            # - name: list files
            #   run: ls
            # - name: Read file
            #   run:  cat README.md
            #   shell: bash