name: Variables and Secrets

on: push

env:           
  DOCKER_USERNAME: pathak
  DOCKER_IMAGENAME: webserver
  DOCKER_TAG: latest

jobs:
  docker:
    runs-on: ubuntu-latest 
    steps:
      - name: Docker Build
        runs: docker build -t $DOCKER_USERNAME/$DOCKER_IMAGENAME:$DOCKER_TAG
      - name: Docker login
        env:
          DOCKER_PASSWD: T@ch@1977
        runs: docker login --username=pathak --password=$DOCKER_PASSWD

      - name: Docker Publish
        runs: docker push pathak/test:latest
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        env:
          DOCKER_PASSWD: T@ch@1977
        runs: docker login --username=pathak --password=$DOCKER_PASSWD
      - name: Docker Deploy
        run: docker run -d -p 8080:80 $DOCKER_USERNAME/$DOCKER_IMAGENAME:$DOCKER_TAG

# JOB LEVEL ENV VARIABLE
#   docker:
#   runs-on: ubuntu-latest
#   env:           
#     DOCKER_USERNAME: pathak
#     DOCKER_IMAGENAME: test
#     DOCKER_TAG: latest
    
#   steps:
#     - name: Docker Build
#       runs: docker build -t $DOCKER_USERNAME/$DOCKER_IMAGENAME:$DOCKER_TAG
#     - name: Docker login
#       env:
#         DOCKER_PASSWD: T@ch@1977
#       runs: docker login --username=pathak --password=$DOCKER_PASSWD

#     - name: Docker Publish
#       runs: docker push pathak/test:latest
# deploy:
#   runs-on: ubuntu-latest
#   env:           
#     DOCKER_USERNAME: pathak
#     DOCKER_IMAGENAME: test
#     DOCKER_TAG: latest
#   steps:
#     - name: Docker login
#       env:
#         DOCKER_PASSWD: T@ch@1977
#       runs: docker login --username=pathak --password=$DOCKER_PASSWD
#     - name: Docker Deploy
#       run: docker run -d -p 8080:80 $DOCKER_USERNAME/$DOCKER_IMAGENAME:$DOCKER_TAG

  #.STEP LEVEL ENV VARIABLE
  # docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Docker Build
  #       env: 
  #         DOCKER_USERNAME: pathak
  #         DOCKER_IMAGENAME: test
  #         DOCKER_TAG: latest
  #       runs: docker build -t $DOCKER_USERNAME/$DOCKER_IMAGENAME:$DOCKER_TAG
  #     - name: Docker login
  #       env:
  #         DOCKER_USERNAME: pathak
  #         DOCKER_PASSWD: T@ch@1977
  #       runs: docker login --username=pathak --password=$DOCKER_PASSWD

  #     - name: Docker Publish
  #       runs: docker push pathak/test:latest
  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Docker Deploy
  #       env:           
  #         DOCKER_USERNAME: pathak
  #         DOCKER_IMAGENAME: test
  #         DOCKER_TAG: latest
  #       run: docker run -d -p 8080:80 $DOCKER_USERNAME/$DOCKER_IMAGENAME:$DOCKER_TAG